apiVersion: apps/v1
kind: Deployment
metadata:
  name: gologger-deployment-fluent-test
  labels:
    app: gologger-deployment-fluent-test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gologger-deployment-fluent-test
  template:
    metadata:
      labels:
        app: gologger-deployment-fluent-test
    spec:
      containers:
      - name: gologger
        image: raymondarias/gologger:0.1.1
        env:
        - name: SLEEP_DURATION
          value: "1ms"
        - name: THREADS
          value: "2"
        - name: APP_ID
          value: "gologgerA"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 200Mi
            cpu: 300m
          requests:
            memory: 100Mi
            cpu: 100m

